# Generated by Django 3.2.5 on 2021-10-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(default='', max_length=225)),
                ('Population', models.IntegerField()),
                ('Cases', models.IntegerField()),
                ('Code', models.CharField(default='', max_length=225)),
            ],
        ),
    ]
