# Generated by Django 3.2.9 on 2022-01-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=225)),
                ('Desc', models.CharField(default='', max_length=225)),
                ('QuantaExhalationRate', models.FloatField(default=0, max_length=225)),
                ('Code', models.CharField(default='', max_length=225)),
                ('Image', models.FileField(blank=True, null=True, upload_to='ActivityLevls')),
                ('Oral_breathing', models.FloatField(default=0, max_length=225)),
                ('Speaking', models.FloatField(default=0, max_length=225)),
                ('Loudly_speaking', models.FloatField(default=0, max_length=225)),
            ],
            options={
                'verbose_name': 'Activity Level',
                'verbose_name_plural': 'Activity Levels',
            },
        ),
        migrations.CreateModel(
            name='ActivityPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=225)),
                ('Floor_Area', models.FloatField(default=0)),
                ('Room_Height', models.FloatField(default=0)),
                ('Code', models.CharField(default='', max_length=225)),
                ('Image', models.FileField(blank=True, null=True, upload_to='ActivityPresets')),
                ('Activity_Level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimate.activitylevels')),
            ],
            options={
                'verbose_name': 'Preset',
                'verbose_name_plural': 'Activity Presets',
            },
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(default='', max_length=225)),
                ('Population', models.IntegerField()),
                ('Cases', models.IntegerField()),
                ('Code', models.CharField(default='', max_length=225)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations Information',
            },
        ),
        migrations.CreateModel(
            name='MaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=225)),
                ('inhalationMaskEfficiency', models.FloatField(default=0)),
                ('exhalationMaskEfficiency', models.FloatField(default=0)),
                ('Code', models.CharField(default='', max_length=225)),
                ('image', models.FileField(blank=True, null=True, upload_to='masks')),
            ],
            options={
                'verbose_name': 'Masks',
                'verbose_name_plural': 'Mask Types',
            },
        ),
        migrations.CreateModel(
            name='result_formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=300)),
                ('upper_value', models.FloatField(default=0)),
                ('lower_value', models.FloatField(default=0)),
                ('Desc', models.CharField(default='', max_length=225)),
                ('image', models.FileField(blank=True, null=True, upload_to='Results')),
            ],
            options={
                'verbose_name': 'Result Type Settings',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Ventilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=225)),
                ('People_Outdoor_Air_Rate', models.FloatField(default=0)),
                ('Area_Outdoor_Air_Rate', models.FloatField(default=0)),
                ('Occupant_Density', models.FloatField(default=0)),
                ('Use_In_Custom', models.BooleanField(default=False)),
                ('Code', models.CharField(default='', max_length=225)),
                ('image', models.FileField(blank=True, null=True, upload_to='VentilationCustoms')),
                ('Activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimate.activitypreset')),
            ],
            options={
                'verbose_name': 'Ventilation Values',
                'verbose_name_plural': 'Ventilation Rates',
            },
        ),
    ]
