# Generated by Django 3.2.5 on 2021-11-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=225)),
                ('Floor_Area', models.FloatField(default=0)),
                ('Room_Height', models.FloatField(default=0)),
                ('Code', models.CharField(default='', max_length=225)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ActivityPresets')),
            ],
            options={
                'verbose_name': 'Preset',
                'verbose_name_plural': 'Activity Presets',
            },
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(default='', max_length=225)),
                ('Population', models.IntegerField()),
                ('Cases', models.IntegerField()),
                ('Code', models.CharField(default='', max_length=225)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations Information',
            },
        ),
        migrations.CreateModel(
            name='MaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=225)),
                ('Code', models.CharField(default='', max_length=225)),
            ],
            options={
                'verbose_name': 'Masks',
                'verbose_name_plural': 'Mask Types',
            },
        ),
        migrations.CreateModel(
            name='Ventilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=225)),
                ('People_Outdoor_Air_Rate', models.FloatField(default=0)),
                ('Air_Outdoor_Air_Rate', models.FloatField(default=0)),
                ('Occupant_Density', models.FloatField(default=0)),
                ('Use_In_Custom', models.BooleanField(default=False)),
                ('Code', models.CharField(default='', max_length=225)),
                ('Activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimate.activitypreset')),
            ],
            options={
                'verbose_name': 'Ventilation Values',
                'verbose_name_plural': 'Ventilation Rates',
            },
        ),
    ]
