# Generated by Django 3.2.5 on 2021-10-27 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationinfo',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations Info'},
        ),
    ]
