# Generated by Django 3.2.5 on 2021-11-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitypreset',
            name='image',
        ),
    ]
