# Generated by Django 3.2.5 on 2021-10-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_alter_locationinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=225)),
                ('Code', models.CharField(default='', max_length=225)),
            ],
            options={
                'verbose_name': 'Preset',
                'verbose_name_plural': 'Activity Presets',
            },
        ),
        migrations.AlterModelOptions(
            name='locationinfo',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations Information'},
        ),
    ]
