# Generated by Django 3.2.5 on 2021-11-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0004_ventilation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='masktype',
            name='exhalationMaskEfficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='masktype',
            name='inhalationMaskEfficiency',
            field=models.FloatField(default=0),
        ),
    ]
