# Generated by Django 3.2.5 on 2021-11-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0005_auto_20211116_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=225)),
                ('Value', models.FloatField(default='', max_length=225)),
                ('Code', models.CharField(default='', max_length=225)),
            ],
        ),
    ]
