# Generated by Django 3.2.5 on 2021-11-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0006_activitylevels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylevels',
            options={'verbose_name': 'Activity Level', 'verbose_name_plural': 'Activity Levels'},
        ),
        migrations.RenameField(
            model_name='activitylevels',
            old_name='Value',
            new_name='QuantaExhalationRate',
        ),
    ]
