# Generated by Django 3.2.5 on 2021-11-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0008_activitylevels_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylevels',
            name='Activity',
        ),
    ]
