# Generated by Django 3.2.5 on 2021-11-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0009_remove_activitylevels_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevels',
            name='Activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimate.activitypreset'),
        ),
    ]
