# Generated by Django 3.2.5 on 2021-11-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0011_auto_20211118_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventilation',
            old_name='Air_Outdoor_Air_Rate',
            new_name='Area_Outdoor_Air_Rate',
        ),
    ]
