# Generated by Django 3.2.5 on 2021-11-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0012_rename_air_outdoor_air_rate_ventilation_area_outdoor_air_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitypreset',
            old_name='Activity',
            new_name='Activity_Level',
        ),
    ]
