# Generated by Django 3.2.9 on 2021-12-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0014_masktype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypreset',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='ActivityPresets'),
        ),
    ]
