# Generated by Django 3.2.9 on 2021-12-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0015_alter_activitypreset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevels',
            name='Desc',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='activitylevels',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='ActivityPresets'),
        ),
    ]
