# Generated by Django 3.2.9 on 2021-12-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0016_auto_20211206_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylevels',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='activitypreset',
            old_name='image',
            new_name='Image',
        ),
    ]
