# Generated by Django 3.2.9 on 2021-12-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0018_alter_activitylevels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masktype',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='masks'),
        ),
    ]
