# Generated by Django 3.2.9 on 2021-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0019_alter_masktype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventilation',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='VentilationCustoms'),
        ),
    ]
