# Generated by Django 3.2.9 on 2021-12-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0021_result_formula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result_formula',
            options={'verbose_name': 'Result Type Settings', 'verbose_name_plural': 'Results'},
        ),
        migrations.AddField(
            model_name='result_formula',
            name='Desc',
            field=models.CharField(default='', max_length=225),
        ),
    ]
