# Generated by Django 3.2.9 on 2022-01-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0022_auto_20211216_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevels',
            name='Loudly_speaking_val',
            field=models.FloatField(default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='activitylevels',
            name='Oral_breathing_val',
            field=models.FloatField(default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='activitylevels',
            name='Speaking_val',
            field=models.FloatField(default=0, max_length=225),
        ),
    ]
