# Generated by Django 3.2.9 on 2022-01-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0023_auto_20220103_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylevels',
            old_name='Loudly_speaking_val',
            new_name='Loudly_speaking',
        ),
        migrations.RenameField(
            model_name='activitylevels',
            old_name='Oral_breathing_val',
            new_name='Oral_breathing',
        ),
        migrations.RenameField(
            model_name='activitylevels',
            old_name='Speaking_val',
            new_name='Speaking',
        ),
    ]
