# Generated by Django 3.2.9 on 2022-01-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0024_auto_20220103_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylevels',
            name='Loudly_speaking',
            field=models.FloatField(default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='activitylevels',
            name='Oral_breathing',
            field=models.FloatField(default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='activitylevels',
            name='QuantaExhalationRate',
            field=models.FloatField(default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='activitylevels',
            name='Speaking',
            field=models.FloatField(default=0, max_length=225),
        ),
    ]
